---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build containers
        run: docker-compose build

      - name: Run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run flake8 lint
        run: docker-compose run --rm app sh -c "flake8"
